name: Bug Report
description: Report a bug in TekkRealm Hub
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    attributes:
      label: Bug summary
      description: Short description of the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: What happened?
      description: Describe the issue in detail
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open TekkRealm Hub
        2. Click on ...
        3. App crashes

  - type: input
    attributes:
      label: App version
      placeholder: e.g. v0.3.1
         
